# Project information
site_name: PhiFormat Documentation
site_description: A fanmade project for the rhythm game "Phigros".
site_author: ZeroAurora
site_url: https://phi-x.github.io/PhiFormat/

# Repository
repo_name: phi-x/PhiFormat
repo_url: https://github.com/phi-x/PhiFormat

# Copyright
copyright: By ZeroAurora & PhiFormat Contributors. Licensed under CC-0.

# Configuration
theme:
  name: material
  language: zh
  palette:
    primary: indigo
    accent: indigo
  features:
    - instant

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

