# Project information
site_name: PhiFormat Documentation
site_description: A fanmade project for the rhythm game "Phigros".
site_author: ZeroAurora
site_url: https://zeroaurora.github.io/PhiFormat/

# Repository
repo_name: ZeroAurora/PhiFormat
repo_url: https://github.com/ZeroAurora/PhiFormat

# Copyright
copyright: By ZeroAurora & PhiFormat Contributors. Licensed under CC-0.

# Configuration
theme:
  name: material
  language: zh
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - instant

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Navigation
nav:
  - "index.md"
  - "简体中文文档":
    - "zh/quick-start.md"